### ISSUE TITLE
two tabs before "TypeError"?

### ISSUE THREAD

**Issue by dansmith65** [geistinteractive/JSONCustomFunctions#31]
I'm not sure how to test if this is correct or not, but the two tab characters before "TypeError" seem like they would break this code.

https://github.com/geistinteractive/JSONCustomFunctions/blob/master/Functions/jsonDelete.fmfn#L41

**Comment by toddgeist** [comment]
did you look in the code, or just the textfile?

**Comment by toddgeist** [comment]
ya it is in the function too
no idea how that got in there. I'll fix it.

**Comment by dansmith65** [comment]
It looks like it's in all the functions that you added the new error checking to.

**Comment by toddgeist** [comment]
its not in all of them... just some of them.
