### ISSUE TITLE
Quotes in strings does not seem to be handled by jsonModify

### ISSUE THREAD

**Issue by Andreas-T** [geistinteractive/JSONCustomFunctions#41]
Without any quotes in the text this works as expected:
`jsonModify ( Test::JSON ; "b" ; "{ \"id\" : 14, \"lnk\" : \"Returned Advanced computing book\" } " )`

Result:
`{
  "a": {
    "id": 12,
    "lnk": 34
  },
  "b": {
    "id": 14,
    "lnk": "Returned Advanced computing book"
  }
}`

However, using quotes in the string like this:
`jsonModify ( Test::JSON ; "b" ; "{ \"id\" : 14, \"lnk\" : \"Returned \"Advanced computing\" book\" } " )
`

Gives this result:
`{
  "a": {
    "id": 12,
    "lnk": 34
  },
  "b": "{ \"id\" : 14, \"lnk\" : \"Returned \"Advanced computing\" book\" } "
}`

Expected result:
`{
	"a" : 
	{
		"id" : 12,
		"lnk" : 34
	},
	"b" : 
	{
		"id" : 14,
		"lnk" : "Returned \"Advanced computing\" book"
	}
}`

**Comment by dansmith65** [comment]
> However, using quotes in the string like this:
jsonModify ( Test::JSON ; "b" ; "{ \"id\" : 14, \"lnk\" : \"Returned \"Advanced computing\" book\" } " )

The 3rd parameter is not valid JSON. You can verify this in one of two ways:

1. Put it in a data viewer and evaluate it to get the non-escaped string, then paste the result into http://jsonlint.com.
2. Build that same json using these custom functions and compare the values.

**Comment by Andreas-T** [comment]
I have tried making a statement using jsonModify to get the expected result, but it does not seem possible, no matter how I escape the quotes.
Would be grateful for advice on how to do this if this is indeed not an issue with the function.
Thanks.

**Comment by Andreas-T** [comment]
It occured to me just after posting my last post that I hadn't escaped the backslash. Thanks for the help.
For anyone in the same situation, here is the correct way to use escaped quotes.

`jsonModify ( Test::JSON ; "b" ; "{ \"id\" : 14, \"lnk\" : \"Returned \\\"Advanced computing\\\" book\" } " )
`

**Comment by davegraham92120** [comment]
You might find it easier to construct all of the JSON elements using jsonModify rather than doing it by hand. 

Example: 

Let ( [ 
	aJSON = jsonModify ( "{}" ; "id" ; 12 ) ; 
	aJSON = jsonModify ( aJSON ; "lnk" ; 34 ) ; 

	bJSON = jsonModify ( "{}" ; "id" ; 14 ) ; 
	bJSON = jsonModify ( bJSON ; "lnk" ; "Return \"Advanced Computing\" book" ) ; 

	JSONOut = jsonModify ( "{}" ; "a" ; aJSON ) ; 
	JSONOut = jsonModify ( JSONOut ; "b" ; bJSON ) 

] ; 
	JSONOut
)
